navbar-links:
    Archive: /archives

avatar: /logo.png
favicon: /logo.png

header:
    title: "Zenobase Blog"
    motto: Collect, aggregate, and visualize your data
    bigimgs:
        - src: /bigimgs/tracks.jpg
          desc:

rss: /atom.xml
googlefonts:
  - "Lora:400,700,400italic,700italic"
  - "Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800"

highlight:
  enable: true
  style_path: "/css/highlight.css"

footer:
  mail:
    link: 'mailto:info@zenobase.com'
    title: Email
    icon: fa-envelope
    enable: true
  linkin:
    link: 'https://www.linkedin.com/company/zenobase'
    title: LinkedIn
    icon: fa-linkedin
    enable: true
  github:
    link: 'https://github.com/zenobase'
    title: GitHub
    icon: fa-github
    enable: true

google_analytics:

comment:
  enable: false
